### ISSUE TITLE
Add enrol base path

### ISSUE THREAD

**Issue by mawiswiss** [motionstudio/enrolzsh#11]
To launch vagrant, we need a simple command to return into the base path

Something like `enrol.base` would be great.

**Comment by scherii** [comment]
Yep, initially I used `.project` and switched to `.base`, too. 🙂

**Comment by mawiswiss** [comment]
Great. `enrol.projects` is already taken. Because autocompletion would work that great with `.project` and `.projects` this was never an option ;-)

**Comment by mawiswiss** [comment]
@scherii Are you using enrol or your original script?

**Comment by scherii** [comment]
My original one – but actually right now no script at all because I'm working on legacy projects. 😄 
Gonna switch to enrol for my next project, tho'.

**Comment by mawiswiss** [comment]
Ah nice.
By the way, you can implement enrol very easily on legacy projects. We also do so for older sites. Even MODX projects are running with enrol.
I have to create some more boilerplate files to get up quickly.
