### ISSUE TITLE
enrol.config.finder does not work on wsl

### ISSUE THREAD

**Issue by j3ll3yfi5h** [motionstudio/enrolzsh#8]
When I use the command "enrol.config.finder" I get "Konnte keinen Dateideskriptor finden, der auf die Konsole verweist.".

Are your commands also compatible to Bash on Windows Subsystem for Linux? ;)

**Comment by mawiswiss** [comment]
No, never tested this.
Fire the following two commands in your windows bash:
`cd ~/.oh-my-zsh/plugins/enrolzsh`
`start .`
Does this work?

**Comment by j3ll3yfi5h** [comment]
nope... :P

**Comment by mawiswiss** [comment]
And this?
`cd ~/.oh-my-zsh/plugins/enrolzsh`
`explorer .`

**Comment by j3ll3yfi5h** [comment]
nope...

**Comment by mawiswiss** [comment]
This thing is dump

**Comment by j3ll3yfi5h** [comment]
>Note: If you try to launch a Windows tool, asking it to open a file that is located in your Linux filesystem, it will be unable to open the file (it will appear to be “missing”) and Bash will inform you of this problem stating that it was : “Unable to translate current working directory. Using C:\WINDOWS\system32”.
>This is due to a current limitation in WSL wherein Windows apps should NOT be used to open files in the Linux filesystem. Opening files in the Windows filesystem is fully supported using both Windows apps and Bash/Linux tools (via /mnt/<drive>/…), but avoid opening Linux files using Windows apps at all cost!

https://blogs.msdn.microsoft.com/commandline/2016/10/19/interop-between-windows-and-bash/

Anyhow, you could add following lines to your config.zsh:
`# Open explorer at global config file`
`enrol.config.explorer() {`
	`eval cmd.exe /C "explorer \"C:\Users\YOUR-WINDOWS-USER\AppData\Local\lxss\home\YOUR-BASH-USER\.oh-my-zsh\plugins\enrolzsh\""`
`}`

**Comment by mawiswiss** [comment]
@j3ll3yfi5h Please test the new windows only command `enrol.config.explorer` to check if the dynamic variables are resolved correctly. I'm not able to test windows the quick way.

**Comment by mawiswiss** [comment]
This approach sadly won't work and is a long way to go. Enrol doesn't officially fully support Windows.

**Comment by Jcambass** [comment]
@marcwieland95 Isn't the real problem here that @j3ll3yfi5h is using bash and not zsh ? 
@j3ll3yfi5h Or did you already try with a ZSH and OH-MY-ZSH Installation on the wls?

**Comment by j3ll3yfi5h** [comment]
@Jcambass of course I'm working with ZSH and OH-MY-ZSH; I changed the default shell to ZSH.

**Comment by Jcambass** [comment]
@j3ll3yfi5h Okei, I was a bit confused there since you've said you'd be using bash on windows. These could have meant that you're literally using bash. However This is a issue that should be fixable since ZSH and Oh-my-zsh are supported on wls. So enrol should be to unless any of it's 3party libs or deps aren't. I'm sure it needs a bit good amount of time to solve this issue and find a workaround. But this should be doable. I'll have a look at that later that week
